### ISSUE TITLE
Missing required attribute homepage

### ISSUE THREAD

**Issue by nxa127** [JeandeCampredon/react-native-SFAuthenticationSession#1]
i got this error
[!] The RNSFAuthenticationSession pod failed to validate due to 1 error:
- ERROR | attributes: Missing required attribute homepage.
- WARN | source: The version should be included in the Git tag.
- WARN | description: The description is equal to the summary.

please add homepage url at RNSFAuthenticationSession.podspec
version: 0.1.1
react-native: 0.61.2

**Comment by neil-gebbie-smarterley** [comment]
Fork the package, go into the podpec and change the empty string from`s.homepage = ""` to the git repo url

**Comment by JeandeCampredon** [comment]
sorry guys I have so much trouble to keep up with my projects but PRs are welcome

**Comment by neil-gebbie-smarterley** [comment]
It's all good. In the event anyone lands here I couldn't get your library to work, so I used https://www.npmjs.com/package/react-native-inappbrowser-reborn
